-- CREATE SCHEMA public;
-- CREATE DATABASE postgres;
-- CREATE SCHEMA IF NOT EXISTS anime
-- CREATE TABLE anime (id SERIAL PRIMARY KEY, name VARCHAR(255));

-- CREATE SCHEMA IF NOT EXISTS anime;
-- CREATE TABLE anime (id SERIAL PRIMARY KEY, name VARCHAR(255));

-- CREATE TABLE IF NOT EXISTS project (
CREATE TABLE project (
        project_id_pk SERIAL PRIMARY KEY,
        project_name VARCHAR(255));
